### ISSUE TITLE
DMPTool and DMPTool Template Clarification Needed

### ISSUE THREAD

**Issue by erinmr** [FAIRIslandProject/Generic-Place-based-Data-Policy#14]
https://github.com/FAIRIslandProject/Generic-Place-based-Data-Policy/blob/a3f0470f6fc439e801c462a2e02959dbb9559d3b/GenericPlacebasedDataPolicy.Rmd#L68

Something is not clicking for me on this. The above says that participants have to use the DMP Tool or equivalent but this says that the Host Organization will provide a template. Would it make more sense to say that Participants are expected to address the following in their DMPs (provide list)? In this way, for whatever tool they are using they can address these rather than going back and forth between a tool and a separate template?

**Comment by erinmr** [comment]
This is a good question about DMP tool specificity. How does the group want to proceed. We could clarify that the host org would provide a template via the DMPTool or could take the suggestion above of DMPs must include x, y, z the tool is agnostic.

**Comment by mariapraetzellis** [comment]
For our project, we'd need them to use the DMPTool to fit it into our workflow. But, going forward, the policy could be platform neutral and allow them to utilize other tools. My preference is to state that the host org will provide a template via the DMPTool & if a specific org wants to modify that section, they can. To generate the types of metadata needed for the workflow we're building at this point, you would need to use the DMPTool since, although Zenodo does mint DMP-IDs, it does not generate the rest of the metadata we're using in our system. I hope that makes sense- we can talk it through as well.
